public class Calculator {
    public void record() {
        
        System.debug('Calculator instance created.');
    }
    public Integer add(integer a, integer b) {
        return a + b;
    }
    public Decimal subtract(Decimal a, Decimal b) {
        return a - b;
    }
    public Decimal multiply(Decimal a, Decimal b) {
        return a * b;
    }
    public Decimal divide(Decimal a, Decimal b) {
        return a / b;
    }
}