integer x = 20;
integer y = 10;
integer sum = x+y;
integer subtract = x-y;
integer multiplication = x*y;
integer division = x/y;

system.debug('sum=' + sum);
system.debug('subtract=' + subtract);
system.debug('multiplication=' + multiplication);
system.debug('division=' + division);

system.debug(sum);
system.debug('sum=' + sum);
system.debug('sum of x,y=' + sum);
system.debug('sum of 10 an 20=' + sum);
system.debug('sum');